### PR TITLE
Fixing fbdev

### PR DESCRIPTION
**Pull request by piranna**
Use fb_vinfo.xres_virtual to define stride. It works on my Lenovo laptop.

### CODE REVIEW

**Comment by piranna** [comment]
:+1:

**Comment by piranna** [comment]
I've managed to find the problem with QEmu framebuffer, it's an issue with the emulated Cirrus graphic card that only allows 24 bits colors while Caire 24 bits format is in fact 32 bits ignoring the alpha channel, so there was a bitrod. I've changed to the `stdvga` emulated graphic cand and use a 32 bits color depth mode and it work flawlessly, so I think the FbDev backend is finished at all :-)

**Comment by ReneHollander** [comment]
Thats good news! I maybe need to look into a better way of detecting the color format from the framebuffer device to create cairo surface.

**Comment by piranna** [comment]
Problem is, Cairo don't support real 24 bits mode... :-/ Don't know if something could be done with the colors masks or some similar trick, but if not, only option for this particular use case will be to have two buffers (one for Cairo and another for framebuffer) and copy and addapt the pixels info between them... :-/ Ideally Cairo should work directly with real 24 bits, but if this is not possible... :-(

**Comment by ReneHollander** [comment]
Hmm. Then I will leave it as is for now...

**Comment by piranna** [comment]
Maybe we can ask Cairo guys...

**Comment by piranna** [comment]
I've been reviewing the code and found we are using a bad 8 bits format too, since A8 is only to define an alpha channel. The same happens with the 1 bit format, so only ones that have a direct translation between Cairo and FbDev are ARGB and 565 modes, and Cairo RGB24 could be easily converted to FbDev 24 bits but with a penalty on performance. I think the best option would be to only allow to use ARGB (32 bits) and 565 (16 bits) modes and throw an exception when trying to use any other format, and "maybe" craft a conversion function for 24 bits. What do you think?

**Comment by ReneHollander** [comment]
Sounds good

**Comment by piranna** [comment]
Done ;-)

**Pull request merged**
